substitutions:
  _REGION: "us-central1"
  _PROJECT_ID: "cours-terraform"
  _REPO_NAME: "dev-rep"
  _IMAGE_NAME: "test-terra-docker"
  _TAG: "latest"

steps:
  # Étape Terraform : Init, Plan et Apply
  - name: 'hashicorp/terraform:latest'
    id: 'Terraform Init and Apply'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform/environments/dev
        terraform init
        terraform plan
        terraform apply -auto-approve

  # Étape Docker : Build de l'image Docker
  - name: 'docker'
    id: 'Build Docker Image'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker build -t $_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$_TAG .

  # Étape Docker : Push de l'image Docker
  - name: 'docker'
    id: 'Push Docker Image'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker push $_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$_TAG

images:
  - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$_TAG'
